name: wechat_assets_picker
description: An audio/video/image picker in pure Dart which is the same with WeChat, support multi picking.
version: 6.2.3
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

  extended_image:
  photo_manager:
  provider:
  video_player:
